on: [push, pull_request]

name: Test

jobs:
  test:
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Check
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run cargo check
        run: cargo check

      - name: Run cargo build
        run: cargo build

      - name: Run cargo doctest
        run: cargo test --doc

      - name: Run cargo test
        run: cargo test
